// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo0DoETr9K78Cp_BuZA3NF_3Hxr7rXirA',
    appId: '1:522075832525:web:f7144f2197856957bc2984',
    messagingSenderId: '522075832525',
    projectId: 'apollon-824ce',
    authDomain: 'apollon-824ce.firebaseapp.com',
    storageBucket: 'apollon-824ce.appspot.com',
    measurementId: 'G-KL35SW2P2S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDel5yLtdhBcD-RlZbJkzGnv4xZhDfi11M',
    appId: '1:522075832525:android:10895fa2b075f6b5bc2984',
    messagingSenderId: '522075832525',
    projectId: 'apollon-824ce',
    storageBucket: 'apollon-824ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvHqS4lkgrNyc2mL5vMKD9bSuwo5MPSto',
    appId: '1:522075832525:ios:b3286e79df269eecbc2984',
    messagingSenderId: '522075832525',
    projectId: 'apollon-824ce',
    storageBucket: 'apollon-824ce.appspot.com',
    iosClientId: '522075832525-jsmo8tjnqf3jbugkkrrpqpttdcanecf9.apps.googleusercontent.com',
    iosBundleId: 'com.example.apollon',
  );
}
